Javascript-javascript2- week1
sunilkumarmahajan/hyf-homework pull request #10
Opened 2021-08-13 11:13 UTC by sunilkumarmahajan

Javascript javascript2 week1

2021-08-16 17:02 UTC, calm-prog reviewed
Hi Sunil, well done! Solid work.
Looking at your code I would say you have a strong understanding of DOM manipulation. You can maybe go a little further next time, and experiment with the optional tasks. 
I also have some specific comments in the code below.

2021-08-16 18:25 UTC, OlkaA requested changes
Hi Sunil

Great job with homework assignment. 👍 

I have some suggestions what could be improved in spiritual animal task:
- instead of `button.innerHTML = "submit"`; you can use
`<button class="submit">Submit</button>`
In this case it is good  distinguishing between markup and logic.
- In `spiritAnimal.innerHTML = ${name} : ${animalNames[Math.floor(Math.random() * 10)]};`
`animalNames[Math.floor(Math.random() * 10)]` gives an 'undefined' sometimes
(Hint: because array animalNames has 9 elements (not 10)).
1) Math.random() returns a number in range from 0 to 1.
2) Math.floor(Math.random() * 10) returns a number from 0 to 9.
3) If it is 9, the item in array does not exist: animalNames[9] = undefined.

Therefore instead of using hardcoded number, fx. "10" (Be aware: in real life, amount of array items _(Read: array.length)_ might change any time, and it is hard to keep in mind hardcoded values (that depends on this array) that need to be changed), you can use dynamic value of array length.

Please let me know if something is unclear :)

2021-08-16 18:32 UTC, OlkaA approved these changes

2021-08-17 20:38 UTC, merged

2021-08-17 20:38 UTC, sunilkumarmahajan commented
changes made as per review