voiceassistant.js added
sunilkumarmahajan/hyf-homework pull request #9
Opened 2021-08-05 16:33 UTC by sunilkumarmahajan

Javascript1 - week4 home work ready for review

2021-08-11 18:49 UTC, zuhairtaha requested changes
Good job.

2021-08-11 18:49 UTC, zuhairtaha commented on javascript/javascript1/week4/voiceassistant.js
> +    else if (command.includes("Add singing"))
Try to make a more dynamic solution to be able to get todo time whatever is it.
hint
```js
    const index1 = _command.indexOf('add ');
    const index2 = _command.indexOf(' to my todo');
    if (index1 !== -1 && index2 !== -1) {
      const todo = _command.substring(index1 + 'add '.length, index2);
}
```
Do the same for removing

2021-08-13 13:04 UTC, sunilkumarmahajan commented on javascript/javascript1/week4/voiceassistant.js
> +        const today = new Date().toDateString().split(" ");
done

2021-08-13 13:05 UTC, sunilkumarmahajan commented on javascript/javascript1/week4/voiceassistant.js
> +       const matharray = command.split(" ");
yes, I made the changes

2021-08-15 10:17 UTC, merged